CLASS zbp_i_bebidas_12 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_bebidas_12.

*PUBLIC SECTION.
*METHODS global_authorization
*  IMPORTING
*    keys TYPE REQUEST FOR GLOBAL AUTHORIZATION
*  RESULT
*    result TYPE RESPONSE FOR GLOBAL AUTHORIZATION.
*
*PRIVATE SECTION.


ENDCLASS.

CLASS zbp_i_bebidas_12 IMPLEMENTATION.



ENDCLASS.
